# Generated by Django 5.0.4 on 2024-05-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='blood_group',
            new_name='bldGrp',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='contact_number',
            new_name='contact',
        ),
    ]
