export const quotes = [
  `"Be a hero in someone's story. Donate blood, save lives."`,
  `"Every pint you give is a lifeline to someone in need. Be the lifeline."`,
  `"The gift of blood is the gift of life. Your generosity knows no bounds."`,
  `"You have the power to be someone's miracle. Donate blood today."`,
  `"One act of kindness, one pint of blood, countless lives saved."`,
  `"Every donor is a silent hero, making a difference one drop at a time."`,
  `"Your blood is the most valuable gift you can give. Share it generously."`,
  `"Every drop counts. Be a hero, donate blood today."`,
  `"Donating blood is the ultimate act of kindness. Be someone's hero."`,
  `"Saving lives starts with you. Donate blood and make a difference."`,
  `"Be the light in someone's darkness. Donate blood, give hope."`,
  `"Your blood has the power to heal. Share it generously, save lives."`,
  `"With every donation, you're giving the gift of life. Be a lifesaver."`,
  `"Heroes come in all types, but blood donors are the true unsung heroes."`,
  `"The world needs more heroes. Donate blood and be part of the solution."`,
  `"One small gesture, one huge impact. Donate blood, be a lifesaver."`,
  `"Giving blood is giving life. Be someone's lifeline, donate today."`,
  `"Your kindness can change the world. Donate blood, make a difference."`,
  `"Be the change you want to see. Donate blood, save lives."`,
  `"Every drop of blood you donate brings hope to someone in need."`,
  `"Blood donors are ordinary people with extraordinary hearts."`,
  `"There's no greater feeling than knowing you've saved a life. Donate blood."`,
  `"Be a part of something bigger than yourself. Donate blood, save humanity."`,
  `"Your blood is a precious gift. Share it with those who need it most."`,
  `"Heroes don't always wear capes. Sometimes, they roll up their sleeves and donate blood."`,
];